### ISSUE TITLE
Analysis checklist

### ISSUE THREAD

**Issue by RandomSearch18** [RandomSearch18/a-level-project#2]
- [x] Identify stakeholders
- [x] #9
- ~~Longer problem definition (?)~~
- [x] Justification of computational approach
- [x] Interview questions
- [x] Ask stakeholders about importance of mobile support
- [x] Look at similar systems
- [x] #4
- [x] #6
- [x] System requitemnts

**Comment by RandomSearch18** [comment]
Analysis submitted!

https://github.com/RandomSearch18/a-level-project/releases/tag/analysis-submission
